parameters:
    sylius.menu_builder.backend.class: Gecko\LegemdaryBundle\Menu\BackendMenuBuilder

services:
    legemdary.form.type.post:
        class: Gecko\LegemdaryBundle\Form\Type\LegemdaryPostType
        tags:
            - { name: form.type, alias: legemdary_post }
    
    legemdary.form.type.diamond_bid:
        class: Gecko\LegemdaryBundle\Form\Type\DiamondBidType
        tags:
            - { name: form.type, alias: legemdary_diamond_bid }
            
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }
            
    legem.send.mailer:
        class: Gecko\LegemdaryBundle\Mailer\SendMailer
        arguments: ["@service_container"]