imports:
    - { resource: @SyliusCoreBundle/Resources/config/app/sylius.yml }
    - { resource: @SyliusCoreBundle/Resources/config/app/payum.yml }
    - { resource: @SyliusCoreBundle/Resources/config/app/cmf.yml }

doctrine_cache:
    providers:
        sylius_settings: %sylius.cache%

knp_gaufrette:
    stream_wrapper: ~
    adapters:
        sylius_image:
            local:
                directory:  %kernel.root_dir%/../web/media/image
                create:     true
        sylius_video:
            local:
                directory:  %kernel.root_dir%/../web/media/video
                create:     true
    filesystems:
        sylius_image:
            adapter: sylius_image
        sylius_video:
            adapter: sylius_video            

vich_uploader:
    db_driver: orm # or mongodb
    gaufrette: true
    storage:   vich_uploader.storage.gaufrette
    mappings:
        video:
            uri_prefix:         /videos
            upload_destination: sylius_video
            delete_on_remove:   true
            delete_on_update:   true
            namer:              vich_uploader.namer_uniqid
        image:
            uri_prefix:         /images
            upload_destination: sylius_image
            delete_on_remove:   true
            delete_on_update:   true
            namer:              vich_uploader.namer_uniqid
            
liip_imagine:
    data_root: %kernel.root_dir%/../web/media/image
    filter_sets:
        sylius_small:
            filters:
                thumbnail: { size: [120, 120], mode: outbound }
        sylius_medium:
            filters:
                thumbnail: { size: [640, 640], mode: outbound }
        sylius_large:
            filters:
                thumbnail: { size: [1024, 1024], mode: outbound }

knp_snappy:
    pdf:
        enabled:    true
        binary:     /usr/bin/wkhtmltopdf
        options:    []
    image:
        enabled:    true
        binary:     /usr/bin/wkhtmltoimage
        options:    []

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.block.service.text: ~

stof_doctrine_extensions:
    default_locale: %sylius.locale%
    orm:
        default:
            tree: true
            sluggable: true
            timestampable: true
            softdeleteable: true
            loggable: true
            sortable: true

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: %sylius.model.user.class%
    group:
        group_class: Sylius\Bundle\CoreBundle\Model\Group
    profile:
        form:
            type: sylius_user_profile
    registration:
        form:
            type: sylius_user_registration

hwi_oauth:
    firewall_name: main
    resource_owners:
        amazon:
            type:          amazon
            client_id:     %sylius.oauth.amazon.clientid%
            client_secret: %sylius.oauth.amazon.clientsecret%
        facebook:
            type:          facebook
            client_id:     %sylius.oauth.facebook.clientid%
            client_secret: %sylius.oauth.facebook.clientsecret%
        google:
            type:          google
            client_id:     %sylius.oauth.google.clientid%
            client_secret: %sylius.oauth.google.clientsecret%
            scope:         "https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile"
            
sylius_resource:
    resources:
        legemdary.post:
            driver: doctrine/orm
            classes:
                model: Gecko\LegemdaryBundle\Entity\LegemdaryPost
