# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
    firewalls:
        administration:
            switch_user: true
            context:     user
            pattern:     /administration/.*
            form_login:
                provider:     fos_userbundle
                login_path:   /administration/login
                check_path:   /administration/login-check
                failure_path: /administration/login
                default_target_path: /administration/dashboard
                use_forward:  false
                use_referer:  true
            logout:
                path:   /administration/logout
                target: /administration/login
            anonymous: true

        main:
            switch_user: { role: ROLE_SYLIUS_ADMIN }
            context:     user
            pattern:     /.*
            form_login:
                provider: fos_userbundle
                login_path: /login
                check_path: /login_check
                failure_path: /login
                default_target_path: /
                use_forward:  false
                use_referer: true
            remember_me:
                key: %sylius.secret%
                name: APP_REMEMBER_ME
                lifetime: 31536000
                always_remember_me: true
                remember_me_parameter: _remember_me
            logout: 
                invalidate_session: false
            anonymous: true

        secured_area:
            pattern:    ^/sinexistir/
            form_login:
                login_path:  /sinexistir/login
                check_path:  /sinexistir/login_check
                default_target_path: /sinexistir/
                always_use_default_target_path: true
            logout:
                path:   /sinexistir/logout
                target: /sinexistir/
            anonymous: ~
            http_basic:
                realm: "Secured Demo Area"
            oauth:
                resource_owners:
                    amazon:   "/sinexistir/login/check-amazon"
                    facebook: "/sinexistir/login/check-facebook"
                    google:   "/sinexistir/login/check-google"
                login_path:   /sinexistir/connect
                check_path:  /sinexistir/login_check
                failure_path: /sinexistir/connect
                oauth_user_provider:
                    service: sylius.oauth.user_provider
                
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        - { path: ^/login.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/connect.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/administration/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/administration/login-check, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "/administration.*", role: [ROLE_SYLIUS_ADMIN, ROLE_SYLIUS_VENDOR] }

        - { path: "/cart.*", role: ROLE_USER }
        - { path: "/account.*", role: ROLE_USER }

        - { path: "/_partial.*", ip: 127.0.0.1 }
