# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_homepage:
    pattern: /home
    defaults: { _controller: sylius.controller.frontend.homepage:mainAction }

sylius_get_pricing_matrix:
    pattern: /get-pricing-matrix
    defaults: { _controller: sylius.controller.frontend.homepage:getPricingMatrixAction }
    
sylius_bid_request:
    pattern: /bid-requested
    defaults: { _controller: sylius.controller.frontend.homepage:bidRequestAction }
    
sylius_coming_soon:
    pattern: /
    defaults: { _controller: sylius.controller.frontend.homepage:comingSoonAction }
    
sylius_diamond_education:
    pattern: /diamond-knowledge
    defaults: { _controller: sylius.controller.frontend.homepage:diamondEducationAction }

sylius_help:
    pattern: /help
    defaults: { _controller: sylius.controller.frontend.homepage:helpAction }
        
sylius_how_it_works:
    pattern: /how-it-works
    defaults: { _controller: sylius.controller.frontend.homepage:howItWorksAction }
   
sylius_our_story:
    pattern: /our-story
    defaults: { _controller: sylius.controller.frontend.homepage:ourStoryAction }

sylius_ring_sizer:
    pattern: /ring-sizer
    defaults: { _controller: sylius.controller.frontend.homepage:ringSizerAction }
         
legemdary_blog:
    pattern: /blog
    defaults: { _controller: sylius.controller.frontend.homepage:blogAction }
    
legemdary_blog_post:
    pattern: /blog/post/{id}
    defaults: { _controller: sylius.controller.frontend.homepage:blogPostAction }
    
sylius_currency:
    resource: @SyliusWebBundle/Resources/config/routing/frontend/currency.yml
    prefix: /currency

sylius_product:
    resource: @SyliusWebBundle/Resources/config/routing/frontend/product.yml
    prefix: /rings

sylius_page:
    resource: @SyliusWebBundle/Resources/config/routing/frontend/page.yml
    prefix: /content

sylius_checkout:
    resource: @SyliusWebBundle/Resources/config/routing/frontend/checkout.yml
    prefix: /checkout

sylius_account:
    resource: @SyliusWebBundle/Resources/config/routing/frontend/account.yml
    prefix: /account

sylius_cart:
    resource: @SyliusCartBundle/Resources/config/routing.yml
    prefix: /cart

sylius_cart_summary:
    pattern: /cart
    defaults:
        _controller: sylius.controller.cart:summaryAction
        _sylius:
            template: SyliusWebBundle:Frontend/Cart:summary.html.twig

sylius_cart_save:
    pattern: /cart/save
    defaults:
        _controller: sylius.controller.cart:saveAction
        _sylius:
            template: SyliusWebBundle:Frontend/Cart:summary.html.twig
